### ISSUE TITLE
Schedule mode fails to track time

### ISSUE THREAD

**Issue by jacobsamlarose** [mutahhir/foldingtext-issues#5] opened 2015-08-11 02:53 UTC
Schedule mode doesn't seem to track time (highlight on time label doesn't move on down the schedule as time progresses) or fire notifications for me. Other than that, schedule displays correctly.

**Comment by mutahhir** [comment] 2015-08-14 17:33
Duplicate of #4. Already fixed. Should be released in the next Dev version.

**Closed as completed by mutahhir** 2015-08-14 17:33 UTC
